<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'PublishPress\\WordPressEDDLicense\\' => array($vendorDir . '/publishpress/wordpress-edd-license/src/classes'),
    'PublishPressPro\\' => array($baseDir . '/../core'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
