<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitPublishPressPro
{
    public static $files = array (
        '3b1e1688e889525de91ac2456aba9efd' => __DIR__ . '/..' . '/publishpress/psr-container/lib/include.php',
        'c92bf23a32412037ecdc51806b458c36' => __DIR__ . '/..' . '/alledia/edd-sl-plugin-updater/EDD_SL_Plugin_Updater.php',
        '24b27b1b9a32bf58eda571c3e5ae3480' => __DIR__ . '/..' . '/publishpress/pimple-pimple/lib/include.php',
        '9c8ea886233d3b80c33afe505e877a57' => __DIR__ . '/..' . '/publishpress/wordpress-edd-license/src/include.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Ctype\\' => 23,
        ),
        'P' => 
        array (
            'PublishPress\\WordPressEDDLicense\\' => 33,
            'PublishPressPro\\' => 16,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'PublishPress\\WordPressEDDLicense\\' => 
        array (
            0 => __DIR__ . '/..' . '/publishpress/wordpress-edd-license/src/classes',
        ),
        'PublishPressPro\\' => 
        array (
            0 => __DIR__ . '/../..' . '/../core',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitPublishPressPro::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitPublishPressPro::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitPublishPressPro::$classMap;

        }, null, ClassLoader::class);
    }
}
