<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '46f34d447a57459d032cc82d3c01b3bb6d33287c',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '46f34d447a57459d032cc82d3c01b3bb6d33287c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'alledia/edd-sl-plugin-updater' => array(
            'pretty_version' => 'v1.6.22',
            'version' => '1.6.22.0',
            'reference' => '56525f1acd28e340f7a7e523638c1424ca7f0e0a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alledia/edd-sl-plugin-updater',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/instance-protection' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '4193f84a8a680bf4c0d40cc64976ddcadd92158a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/instance-protection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/pimple-pimple' => array(
            'pretty_version' => '3.5.0.10',
            'version' => '3.5.0.10',
            'reference' => 'f2784f4b1ccaf195b373a46a74cf3742e7c9f826',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/pimple-pimple',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/psr-container' => array(
            'pretty_version' => '2.0.1.10',
            'version' => '2.0.1.10',
            'reference' => '4ccd2cb058e7b93e96186791ca25870a02e35c5d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/psr-container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/publishpress' => array(
            'pretty_version' => 'v3.11.0',
            'version' => '3.11.0.0',
            'reference' => '21482d8d03e26c53db1461c6976feb1c94b80d08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/publishpress',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'publishpress/wordpress-edd-license' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'ea53f02c0537bf4054bf3fcb183f93a08c0b2ed3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../publishpress/wordpress-edd-license',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'reference' => 'aed596913b70fae57be53d86faa2e9ef85a2297b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
