name: Deploy to Pantheon
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build and push to Pantheon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup-runner
        name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          pantheon_ssh_key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          ssh_config: ${{ secrets.SSH_CONFIG }}
          pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          php_version: '7.4'
          composer_version: 'v2'
          terminus_version: '^2.0'
          node_version: '16'

      - name: Composer Install Dependencies
        run: composer install --working-dir=dev-tools/pro --optimize-autoloader --no-dev --prefer-dist --no-progress --no-suggest

      - name: Move plugins
        run: mv -f dev-tools/pro/wp-content/plugins/* wp-content/plugins/

      - name: Move theme
        run: mv -f dev-tools/pro/wp-content/themes/* wp-content/themes/

      # Build Theme
      - run: cd wp-content/themes/collectivewp && npm install

      - name: Compile theme assets
        run: cd wp-content/themes/collectivewp && npm run build

      - name: Remove node_modules
        run: cd wp-content/themes/collectivewp && rm -rf node_modules

      ## Prepare for Pantheon
      - name: Prepare for Pantheon
        run: find ./ -type d -name ".git .github .wpe*" | xargs rm -fr

      ## Deploy
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.PANTHEON_USERNAME }}
            server: ${{ secrets.PANTHEON_HOST }}
            password: ${{ secrets.PANTHEON_PASSWORD }}
            port: 2222
            local_path: './wp-content/*'
            remote_path: '~/code/wp-content/'
            sftpArgs: '-o ConnectTimeout=5'

      # - name: Notify Slack
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #       SLACK_CHANNEL: client-collectivewp
      #       SLACK_COLOR: ${{ job.status }}
      #       SLACK_ICON: https://avatars.slack-edge.com/2021-09-02/2472786275504_23fa532873531951ddd3_32.png
      #       SLACK_USERNAME: Github
      #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #       SLACK_FOOTER: ${{ github.repository }}
